server:
  port: 8501


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cassandra:
    contact-points: localhost
    username: cassandra
    password: cassandra
    keyspace-name: spring cloud
    port: 9042
  boot:
    admin:
      client:
        url: http://localhost:8508

  management:
    endpoints:
      web:
        exposure:
          include: "*"