server:
  port: 8502


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ticket-service
  datasource:
    password: microservices-app
    url: jdbc:mysql://localhost:3306/microservicesapp
    username: root
  jpa:
    hibernate:
      dll-auto: update
  rabbitmq:
    username: yasinenessisik
    password: yasinenessisik
  cloud:
    stream:
      binding:
        output:
          destination: msqueue
  boot:
    admin:
      client:
        url: http://localhost:8508
management:
  endpoints:
    web:
      exposure:
        include: "*"