server:
  port: 8761
spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:8508

  management:
    endpoints:
      web:
        exposure:
          include: "*"